accounts:
  msg: Welcome to the EazyBank Accounts Default application
  build-version: 2

  mailDetails:
    hostName: default-accounts@eazybytes.com
    port: 9020
    from: default-accounts@eazybytes.com
    subject: Your Account Details from Eazy Bank Default Environment

  activeBranches:
    - Mumbai
    - London
    - Washington