server:
  port: 8088

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    defaultZone: http://localhost:8088/eureka/